#####Stage 3#####
Here is the configuration of this run: 
Munch({'exp_name': 'performance on short sequences', 'conserved': True, 'gpu': '0,1,2,3', 'u_net_d': 10, 'BATCH_SIZE': 8, 'batch_size_stage_1': 20, 'batch_size_stage_2': 16, 'OUT_STEP': 100, 'LOAD_MODEL': True, 'pp_steps': 20, 'pp_loss': 'f1', 'pp_model': 'mixed', 'rho_per_position': 'matrix', 'data_type': 'Rfam_14.5_synthetic_600', 'model_type': 'att_simple_fix', 'epoches_first': 50, 'epoches_second': 10, 'epoches_third': 10, 'evaluate_epi': 1, 'evaluate_epi_stage_1': 5, 'step_gamma': 1, 'k': 1, 'test': Munch({'f1': True, 'accuracy': False, 'energy': False})})
Max seq length  600
Loading u net model...
Traceback (most recent call last):
  File "/g/data/ik06/jiajia/e2efold_for_rfam/experiment_rfam/e2e_learning_stage3.py", line 275, in <module>
    pred_contacts, a_pred_list = rna_ss_e2e(PE_batch, seq_embedding_batch, state_pad, conservation_batch)
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
NameError: Caught NameError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/g/data/ik06/e2efold_for_rfam/e2efold_rfam/models.py", line 1101, in forward
    map_list = self.model_pp(u, seq, conservation_batch)
  File "/home/248/jx3129/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/g/data/ik06/e2efold_for_rfam/e2efold_rfam/models.py", line 787, in forward
    m1=self.constraint_matrix_conserved_batch(x,conservation_batch) # Ratio Matrix
  File "/g/data/ik06/e2efold_for_rfam/e2efold_rfam/models.py", line 867, in constraint_matrix_conserved_batch
    m = au_ua + cg_gc + ug_gu + ag_ga + ac_ca + aa_aa + gg_gg + uu_uu + uc_cu + cc_cc
NameError: name 'ag_ga' is not defined

